tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-card": "#FFFFFF",
        "text-muted": "#64748B",
        "on-tertiary-fixed": "#410006",
        "secondary": "#4d5f7d",
        "on-surface-variant": "#3c4947",
        "gradient-end": "#3B82F6",
        "on-tertiary-fixed-variant": "#8c1520",
        "gradient-start": "#14B8A6",
        "primary-container": "#14b8a6",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface": "#f7f9fb",
        "surface-container-high": "#e6e8ea",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e0e3e5",
        "on-primary-container": "#00423b",
        "outline-variant": "#bbcac6",
        "on-secondary-container": "#4e607e",
        "on-secondary-fixed-variant": "#354764",
        "on-primary-fixed": "#00201c",
        "tertiary": "#ae2f34",
        "secondary-fixed-dim": "#b5c7ea",
        "tertiary-fixed-dim": "#ffb3b0",
        "outline": "#6c7a77",
        "inverse-surface": "#2d3133",
        "surface-container": "#eceef0",
        "tertiary-container": "#ff7c7a",
        "surface-container-highest": "#e0e3e5",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#ffdad8",
        "background": "#f7f9fb",
        "on-error": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        "on-surface": "#191c1e",
        "surface-tint": "#006b5f",
        "secondary-container": "#c8dbfe",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#4fdbc8",
        "surface-bright": "#f7f9fb",
        "on-tertiary-container": "#7a0315",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#005048",
        "primary": "#006b5f",
        "error": "#ba1a1a",
        "inverse-primary": "#4fdbc8",
        "on-secondary-fixed": "#071c36",
        "on-background": "#191c1e",
        "surface-dim": "#d8dadc",
        "secondary-fixed": "#d5e3ff",
        "primary-fixed": "#71f8e4"
      },
      borderRadius: { DEFAULT: "1rem", lg: "2rem", xl: "3rem", full: "9999px" },
      spacing: { "margin-mobile": "20px", gutter: "24px", "margin-desktop": "40px", base: "8px", "section-gap": "64px" },
      fontFamily: {
        "display-lg": ["Montserrat"], "headline-md": ["Montserrat"], "label-sm": ["Montserrat"],
        "label-md": ["Montserrat"], "headline-lg-mobile": ["Montserrat"], "headline-lg": ["Montserrat"],
        "body-lg": ["Montserrat"], "body-md": ["Montserrat"]
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-md": ["20px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.4", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["26px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }]
      }
    }
  }
};
